language: java
install:
- mvn install
jdk:
- oraclejdk8
deploy:
  provider: heroku
  api_key:
    secure: Ofrmns6yVY5MiJKOmUgLf1gBYVRVpRIQjximk5xF0WHCi9LvLpWzVA8nJUoF/RccMsZoIa6axQteekl67XIeCnscCwhXpnP4Wdq10qGTBa/wqTYR/Ls0jBB2/lA4GfxrAazjG6CeZgLKgcBQul61RWll261+gOmfj2vsDxNn1DdX9XArqvZKi8tHO4Iruq0R6pG6AmD3XxNHOXnVQ7TkXPKbX7xCn5HUmcHnTqFdMnVb5yQCyDlqOsidkP+3flnri+x6ia2qFL1Jxw/2JJgZqsrOa4RUqkz8LFQuSu7mlo92MBWR4CjiqgrCxqzDsKFwlFlRdrhPcHAtfjaLzklnmJtckdTr5Wbu2SoazQ8a/yx4iBB3ihS/Ubi9zBLnEoNMHLI3pVKkNgfLDBC6mqvn/N9Lo/EZlMxct+zwBYrqyM81uyu61QSXS5fWYhfWemsV3yufWK07ToXCbhkLOu7Q1Qw127oSTuhokrGLDmO7xdxKvzwFTQs0+iqcRlcVcnvq21E+WkmC71EPtjwHLuylHHX4mEF7qngU+CtfsFiHMVYn8TWKh4fDmg3WpWxnlO2rf/1D8Mk51q6FOEXGFqCOiLoKKUbolWrgjjL4St44L0STUatrCSPgSDXHjTf9MdZtA0QuS5UkZeTGTb298teTSblnGmgkD0W0AF9GDsOl6VE=
  app: rdpi-addressbook
  on:
    repo: rdpi/addressbook
    branch: todo_tasks
